[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "../../about-us"
  to = "/page/about-us/about-us.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/page/blog/blog.html"
  status = 200

[[redirects]]
  from = "/contact-us"
  to = "/page/contact-us/contact-us.html"
  status = 200

[[redirects]]
  from = "/portofolio"
  to = "/page/portofolio/portofolio.html"
  status = 200

[[redirects]]
  from = "/subscription"
  to = "/page/subscription/subscription.html"
  status = 200

[[redirects]]
  from = "/about-us"
  to = "/page/about/about-us.html"
  status = 200